export const corsOptions = {
    origin: [
        'https://localhost:4200',
        'http://localhost:4200',
        'https://localhost:5173',
        'http://localhost:5173',
        'http://localhost:8843',
        'http://localhost:8880',
    ],
    allowMethods: ['GET', 'HEAD', 'POST', 'PUT', 'DELETE'],
    allowedHeaders: [
        'Origin',
        'Accept',
        'Content-Type',
        'Authorization',
        'Allow',
        'Content-Length',
        'Date',
        'If-Match',
        'If-Not-Match',
        'sec-fetch-mode',
        'sec-fetch-site',
        'sec-fetch-dest',
    ],
    maxAge: 86_400,
    exposedHeaders: [
        'Content-Type',
        'Content-Length',
        'ETag',
        'Location',
        'Date',
        'Last-Modified',
        'Access-Control-Allow-Origin',
        'Content-Security-Policy',
        'Strict-Transport-Security',
        'X-Content-Type-Options',
    ],
};
